# infrastructure.yaml
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CalculatorAppECSCluster:
    Type: AWS::ECS::Cluster
    Properties: {}

  CalculatorAppTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: calculator-app
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      ContainerDefinitions:
        - Name: calculator-app
          Image: calculator-app:latest
          Essential: true
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp

  CalculatorAppService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref CalculatorAppECSCluster
      DesiredCount: 1
      TaskDefinition: !Ref CalculatorAppTaskDefinition
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - subnet-0bb1c79de3EXAMPLE
          SecurityGroups:
            - sg-04f8d0473bEXAMPLE
          AssignPublicIp: ENABLED
