name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: | 
        python -m unittest test_calculator.py

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Specify the region you want to use

    - name: Create S3 bucket
      run: |
        # aws s3api create-bucket --bucket clear-newbbucketq --region us-east-1 --create-bucket-configuration LocationConstraint=us-east-1
        # aws s3api create-bucket --bucket clear-newbbucketq --region us-east-1
        ls
        aws cloudformation deploy --stack-name "test-ecs-stack" --template-file ./infrastructure.yaml" --region us-east-1 --capabilities CAPABILITY_IAM
    - name: Deploy to AWS
      run: |
        # Replace with actual deployment steps to AWS
        echo "Deploy steps placeholder"
